export interface Country {
  updated:number;
  country:string;
  countryInfo:Object;
  cases:number;
  todayCases:number;
  deaths:number;
  todayDeaths:number;
  recovered:number;
  todayRecovered:number;
  active:number;
  critical:number;
  casesPerOneMillion:number;
  deathsPerOneMillion:number;
  tests:number;
  testsPerOneMillion:number;
  population:number;
  continent:string;
  oneCasePerPeople:number;
  oneDeathPerPeople:number;
  oneTestPerPeople:number;
  acivePerOneMillion:number;
  recoveredPerOneMillion:number;
  criticalPerOneMillion:number;
}
